### PR TITLE
optimize mount logic && fix calculating ufs total size for JindoRuntime

### LINKED ISSUE #4273: [BUG] Incorrect UFS total size when setting `spec.mounts[].path` with JindoRuntime
**What is your environment(Kubernetes version, Fluid version, etc.)**
Fluid v1.0.1

**Describe the bug**
The Dataset bound with JindoRuntime shows "0.00B" UFS Total size, but UFS is not empty.
```
NAME    UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE   AGE
demo2   0.00B            0.00B    2.00GiB          0.0%                Bound   107s
```

This bug occurs when explicitly setting `Dataset.spec.mounts[*].path` to a non-root path, for example:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: demo2
spec:
  placement: Shared
  accessModes:
  - ReadOnlyMany
  mounts:
      mountPoint: <mountPoint>
      name: demo2
      path: /mybucket
```

**What you expect to happen:**
`Dataset.Status.UfsTotalSize` should be calculated properly.

**How to reproduce it**
1. create a dataset with `spec.mounts[*].path`
2. create a JindoRuntime, and bind it to the dataset.

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
Code changes in this PR:
- refactor `UFSPathBuilder` to make it reused by all the cache systems with a Unified Namespace. (i.e. Alluxio, GooseFS and JindoFS)
- bugfix for #4273 
- optimize code logic for functions of JindoFsxEngine and JindoCacheEngine.

### Ⅱ. Does this pull request fix one issue?

fixes #4273 

### Ⅴ. Special notes for reviews
There is a corner case that backward incompatibility may happen in this PR. Please have a loot at my comment below for more information.

### CODE REVIEW

File: pkg/ddc/jindofsx/ufs_internal.go [hunk 1]
```diff
@@ -86,14 +86,8 @@ func (e *JindoFSxEngine) mountUFS() (err error) {
...
-					return err
-				}
-				continue
-			}
-			err = fileUitls.Mount(mount.Name, mount.MountPoint)
+			mountPathInJindo := utils.UFSPathBuilder{}.GenUFSPathInUnifiedNamespace(mount)
+			err = fileUitls.Mount(mountPathInJindo, mount.MountPoint)
 			if err != nil {
 				return err
 			}
```
Comment (TrafalgarZZZ) [inline pkg/ddc/jindofsx/ufs_internal.go:93]: A corner case of backward incompatibility is not handled here. Previous implementation allows users to define `mount.Path` without a prefix "/", and `JindoEngine` passes `mount.Path` to `JindoFileUtils.Mount()`. Inside `JindoFileUtils.Mount()`, the function automatically add a prefix "/" to `mount.Path` and try to mount on it.

That is to say, if a user used to set `Dataset.spec.mounts[*].path` to a string without a prefix "/", he or she may see different behavior  before and after this PR is merged. For example:
```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: demo2
spec:
  placement: Shared
  accessModes:
  - ReadOnlyMany
  mounts:
      mountPoint: <mountPoint>
      name: demo2 # After this pr is merged, mountPoint is mounted to /demo2
      path: mybucket # Before this pr is merged, mountPoint is mounted to /mybucket
```

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
