### PR TITLE
pass AccessModes to thinruntime fuse container

### LINKED ISSUE #3636: [BUG] AccessModes is not passed to ThinRuntime fuse container.
**What is your environment(Kubernetes version, Fluid version, etc.)**
Kubernetes version: 1.28
Fluid version: 1.0.0-45ba742e

**Describe the bug**
When using `ThinRuntime` for mounting fuse file system, the `AccessModes` is not passed as a parameter into fuse container (`/etc/fluid/config.json` and `/etc/fluid/runtime.json`). So users cannot use `AccessModes` to restrict readWrite mode.

**What you expect to happen:**
Add `AccessModes` to `/etc/fluid/config.json`.

**How to reproduce it**
Any thinRuntime addon can reproduce it.

**Additional Information**
In [this code](https://github.com/fluid-cloudnative/fluid/blob/25212a06d358c31b0aba3d7e8c9951e289822beb/pkg/ddc/thin/transform_config.go#L73), `accessModes` in `dataset` is not append to config file.

### PR DESCRIPTION
**Pull request by xliuqq**
### Ⅰ. Describe what this PR does
pass AccessModes to thinruntime fuse container

### Ⅱ. Does this pull request fix one issue?

fixes #3636

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/thin/transform_fuse_test.go [hunk 1]
```diff
@@ -705,7 +706,7 @@ func TestThinEngine_transformFuseWithDuplicateOptionKey(t1 *testing.T) {
 			}},
 			// ConfigValue: "{\"/thin/fluid/test/thin-fuse\":\"a=b\"}",
 			// MountPath:   "/thin/fluid/test/thin-fuse",
-			ConfigValue:   "{\"mounts\":[{\"mountPoint\":\"abc\",\"options\":{\"a\":\"b\"}}],\"targetPath\":\"/thin/fluid/test/thin-fuse\"}",
+			ConfigValue:   "{\"mounts\":[{\"mountPoint\":\"abc\",\"options\":{\"a\":\"b\"}}],\"targetPath\":\"/thin/fluid/test/thin-fuse\",\"accessModes\":[\"ReadOnlyMany\"]}",
```
Comment (cheyang) [inline pkg/ddc/thin/transform_fuse_test.go:709]: Could you add a test with accessModes as ReadWriteMany?

Comment (xliuqq) [reply pkg/ddc/thin/transform_fuse_test.go:709]: see above code line 490,  accessModes as ReadWriteMany.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
