### PR TITLE
<Normalize_comments_on_func_SetupMaster>

### LINKED ISSUE #311: [BUG] Normalization of annotations on func SetupMaster(pkg/ddc/alluxio/master.go
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by liutumor**
### Ⅰ. Describe what this PR does
Normalization of annotations on func SetupMaster(pkg/ddc/alluxio/master.go)

### Ⅱ. Does this pull request fix one issue?

fixes #311

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by cheyang** [comment]
Please open an issue first, then fix it by PR. Thanks.

File: pkg/ddc/alluxio/master.go [hunk 1]
```diff
@@ -113,7 +113,9 @@ func (e *AlluxioEngine) ShouldSetupMaster() (should bool, err error) {
 	return
 }
 
-// setup the cache master
+// SetupMaster setup the master and Update the status of the runtime
```
Comment (cheyang) [inline pkg/ddc/alluxio/master.go:116]: setup the master and Update the status -> setups the master and updates the status

**Review by cheyang — CHANGES_REQUESTED** [review]

**Review by cheyang — APPROVED** [review]
