### PR TITLE
fix dataoperation when nil

### LINKED ISSUE #3258: [BUG] when OperationRef[operationType] is nil, SetDataOperationInProgress  failed.
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by zwwhdls**
### Ⅰ. Describe what this PR does
fix when OperationRef[operationType] is nil, `SetDataOperationInProgress ` failed.

### Ⅱ. Does this pull request fix one issue?

fixes #3258 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

File: api/v1alpha1/dataset_types.go [hunk 1]
```diff
@@ -347,7 +347,7 @@ func (dataset *Dataset) GetDataOperationInProgress(operationType string) string
 
 // SetDataOperationInProgress set the data operation running on this dataset,
 func (dataset *Dataset) SetDataOperationInProgress(operationType string, name string) {
-	if dataset.Status.OperationRef == nil {
+	if dataset.Status.OperationRef == nil || dataset.Status.OperationRef[operationType] == "" {
 		dataset.Status.OperationRef = map[string]string{
```
Comment (xliuqq) [inline api/v1alpha1/dataset_types.go:351]: The `OperationRef[operationType]` nil check is wrong under the following case:

1. dataload A initialize the OperationRef from nil to {"dataload": "A"};
2. datamigrate B the will set the OperationRef to {"datamigrate": ",B"}, the dataload 'A' is missed;

Comment (zwwhdls) [reply api/v1alpha1/dataset_types.go:351]: fixed in https://github.com/fluid-cloudnative/fluid/pull/3261
