### PR TITLE
bugfix: reconcile thinruntime failed when dataset is deleted

### LINKED ISSUE #3295: [BUG] Failed on Reconcile thinruntime when dataset is deleted
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
Failed on reconcile thinruntime when dataset is deleted

**What you expect to happen:**
No error is raised because dataset is deleted

**How to reproduce it** 

**Additional Information**

### PR DESCRIPTION
**Pull request by wangshli**
### Ⅰ. Describe what this PR does
bugfix: reconcile thinruntime failed when dataset is deleted

### Ⅱ. Does this pull request fix one issue?

fixes #3295 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/controllers/runtime_controller.go [hunk 1]
```diff
@@ -87,17 +87,17 @@ func (r *RuntimeReconciler) ReconcileInternal(ctx cruntime.ReconcileRequestConte
 		return utils.RequeueIfError(errors.Wrap(err, "Failed to create"))
 	}
 
-	// 2.Get or create the engine
-	engine, err := r.implement.GetOrCreateEngine(ctx)
+	// 2.Get the ObjectMeta of runtime
```
Comment (cheyang) [inline pkg/controllers/runtime_controller.go:90]: Could you add comments about the reason of changing the order of step 2 and 3?

Comment (wangshli) [reply pkg/controllers/runtime_controller.go:90]: Changing the order was used to judge GetOrCreateEngine failed reason which is runtime having deletionTimeStamp.  In this case we should ignore the GetOrCreateEngine error and continue to reconcileruntimeDeletion, but it would cause engine is a nil pointer. And we have resolvd this problem inside GetOrCreateEngine so that it would return an engine although it could not get mounted dataset. So the order is no need to change now and i will fix it.

File: pkg/ddc/base/dataset_test.go [hunk 2]
```diff
@@ -79,7 +79,7 @@ func TestGetMountedDatasetNamespacedName(t *testing.T) {
 		},
 	}
 	for _, tt := range tests {
-		if got := GetMountedDatasetNamespacedName(tt.virtualDataset); len(got) != tt.want {
+		if got := GetMountedDatasetNamespacedName(tt.virtualDataset.Spec.Mounts); len(got) != tt.want {
```
Comment (cheyang) [inline pkg/ddc/base/dataset_test.go:82]: How about renaming the function name to `GetPhysicalDatasetFromMounts`?

File: pkg/ddc/thin/engine.go [hunk 3]
```diff
@@ -117,10 +117,21 @@ func Precheck(client client.Client, key types.NamespacedName) (found bool, err e
 func CheckReferenceDatasetRuntime(client client.Client, runtime *datav1alpha1.ThinRuntime) (bool, error) {
 	dataset, err := utils.GetDataset(client, runtime.Name, runtime.Namespace)
 	if err != nil {
-		return false, err
+		if utils.IgnoreNotFound(err) == nil && runtime.Status.Mounts != nil && len(runtime.Status.Mounts) != 0 {
```
Comment (cheyang) [inline pkg/ddc/thin/engine.go:120]: I think we should make it work even the virtualDataset is deleted.

Comment (wangshli) [reply pkg/ddc/thin/engine.go:120]: Normally, the virtualDataset would not be deleted because its reference runtime has not been cleaned up.

Comment (cheyang) [reply pkg/ddc/thin/engine.go:120]: But it may happen when deleting virtualDataset forcely.  How to handle this then?

File: pkg/ddc/base/dataset_test.go (hunk 2 above)
Comment (wangshli) [reply pkg/ddc/base/dataset_test.go:82]: ok

File: pkg/ddc/thin/engine.go (hunk 3 above)
Comment (wangshli) [reply pkg/ddc/thin/engine.go]: fixed

File: pkg/ddc/thin/engine.go [hunk 4]
```diff
@@ -116,11 +116,19 @@ func Precheck(client client.Client, key types.NamespacedName) (found bool, err e
...
+	if err != nil && utils.IgnoreNotFound(err) != nil {
+		// ignore dataset not found err and try to get mounted dataset from runtime
 		return false, err
 	}
 
-	mounted := base.GetMountedDatasetNamespacedName(dataset)
+	var mounted []types.NamespacedName
+	if dataset != nil {
+		// getMountedDataset from dataset first
+		mounted = base.GetPhysicalDatasetFromMounts(dataset.Spec.Mounts)
```
Comment (cheyang) [inline pkg/ddc/thin/engine.go:127]: I suggest adding  more logging info for debugging.

File: pkg/ddc/thin/engine.go [hunk 5]
```diff
@@ -116,11 +116,19 @@ func Precheck(client client.Client, key types.NamespacedName) (found bool, err e
...
+	} else if runtime.Status.Mounts != nil && len(runtime.Status.Mounts) != 0 {
+		// then try to getMountedDataset from runtime
+		mounted = base.GetPhysicalDatasetFromMounts(runtime.Status.Mounts)
+	}
```
Comment (cheyang) [inline pkg/ddc/thin/engine.go:131]: What will happen if dataset is not found and the length of runtime mounts  is 0? How will the user handle this situation?

File: pkg/ddc/thin/engine.go (hunk 4 above)
Comment (wangshli) [reply pkg/ddc/thin/engine.go:136]: Done.

File: pkg/ddc/thin/engine.go [hunk 6]
```diff
@@ -124,15 +132,39 @@ func CheckReferenceDatasetRuntime(client client.Client, runtime *datav1alpha1.Th
...
+		ctx.Log.V(1).Info("Virtual dataset not found, try to get physical dataset from runtime mounts")
 		mounted = base.GetPhysicalDatasetFromMounts(runtime.Status.Mounts)
 	}
 	// not mount other datasets
 	if len(mounted) == 0 {
 		return false, nil
 	}
 
+	// patch runtime with reference annotation
+	_, err = PatchReferenceThinRuntimeAnnotation(ctx.Client, runtime)
```
Comment (cheyang) [inline pkg/ddc/thin/engine.go:148]: I suggest moving PatchReferenceThinRuntimeAnnotation to another PR.

Comment (wangshli) [reply pkg/ddc/thin/engine.go:148]: OK

File: pkg/ddc/thin/engine.go [hunk 7]
```diff
@@ -114,13 +114,23 @@ func Precheck(client client.Client, key types.NamespacedName) (found bool, err e
 }
 
 // CheckReferenceDatasetRuntime judge if this runtime is used for handling dataset mounting another dataset.
-func CheckReferenceDatasetRuntime(client client.Client, runtime *datav1alpha1.ThinRuntime) (bool, error) {
-	dataset, err := utils.GetDataset(client, runtime.Name, runtime.Namespace)
-	if err != nil {
+func CheckReferenceDatasetRuntime(ctx cruntime.ReconcileRequestContext, runtime *datav1alpha1.ThinRuntime) (bool, error) {
+	dataset, err := utils.GetDataset(ctx.Client, runtime.Name, runtime.Namespace)
+	if err != nil && utils.IgnoreNotFound(err) != nil {
+		// ignore dataset not found err and try to get mounted dataset from runtime
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/engine.go:120]: I think the comment should be added below? This is the case which does not ignore error.

File: pkg/ddc/thin/referencedataset/runtime.go [hunk 8]
```diff
@@ -91,20 +96,39 @@ func (e *ReferenceDatasetEngine) getRuntimeInfo() (base.RuntimeInfoInterface, er
...
 	if err != nil {
 		return e.mountedRuntimeInfo, err
 	}
 
-	mountedNameSpacedNames := base.GetMountedDatasetNamespacedName(dataset)
+	var mountedNameSpacedNames []types.NamespacedName
+	if dataset != nil {
+		// get mountedRuntimeInfo from dataset first
+		mountedNameSpacedNames = base.GetPhysicalDatasetFromMounts(dataset.Spec.Mounts)
+	} else if runtime.Status.Mounts != nil && len(runtime.Status.Mounts) != 0 {
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/referencedataset/runtime.go:124]: No need to check `runtime.Status.Mounts != nil` here because `len(nil) == 0`. We can remove `runtime.Status.Mounts != nil` to avoid code redundancy

**Review by TrafalgarZZZ — CHANGES_REQUESTED** [review]

File: pkg/ddc/thin/referencedataset/runtime.go (hunk 8 above)
Comment (wangshli) [reply pkg/ddc/thin/referencedataset/runtime.go]: Done.

File: pkg/ddc/thin/referencedataset/runtime.go [hunk 9]
```diff
@@ -91,22 +96,40 @@ func (e *ReferenceDatasetEngine) getRuntimeInfo() (base.RuntimeInfoInterface, er
 	e.Log.Info("Setup with dataset done", "exclusive", e.runtimeInfo.IsExclusive())
 
 	return e.runtimeInfo, nil
-
 }
 
+// getMountedRuntimeInfo get mountedRuntimeInfo from dataset.
+// If could not get dataset, getMountedRuntimeInfo try to get mountedRuntimeInfo from runtime status.
 func (e *ReferenceDatasetEngine) getMountedRuntimeInfo() (base.RuntimeInfoInterface, error) {
 	if e.mountedRuntimeInfo != nil {
```
Comment (cheyang) [inline pkg/ddc/thin/referencedataset/runtime.go:104]: Please add comment: // If already have mountedRuntimeInfo, return it directly

File: pkg/ddc/thin/engine.go [hunk 10]
```diff
@@ -115,26 +115,25 @@ func Precheck(client client.Client, key types.NamespacedName) (found bool, err e
...
-		// get physicalDataset from dataset first
-		ctx.Log.V(1).Info("Get physical dataset from virtual dataset mounts")
-		physicalDataset = base.GetPhysicalDatasetFromMounts(dataset.Spec.Mounts)
-	} else if len(runtime.Status.Mounts) != 0 {
-		// Virtual dataset not found, try to get physicalDataset from runtime
-		ctx.Log.V(1).Info("Virtual dataset not found, try to get physical dataset from runtime mounts")
-		physicalDataset = base.GetPhysicalDatasetFromMounts(runtime.Status.Mounts)
+	dataset, err := utils.GetDataset(ctx.Client, runtime.Name, runtime.Namespace)
+	if err != nil {
+		return false, err
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/engine.go:129]: We should not return every error here because in cases where `len(runtime.Status.Mounts) == 0` && `Dataset not found`, the func will return error to keep engine building failed.

File: pkg/ddc/thin/referencedataset/engine.go [hunk 11]
```diff
@@ -186,55 +192,64 @@ func (e *ReferenceDatasetEngine) Setup(ctx cruntime.ReconcileRequestContext) (re
...
+	physicalRuntimeInfo, err := e.getPhysicalRuntimeInfo()
+	if err != nil && utils.IgnoreNotFound(err) != nil {
 		return err
 	}
 
-	if utils.ContainsString(mountedDataset.Status.DatasetRef, datasetRefName) {
-		newDataset := mountedDataset.DeepCopy()
-		newDataset.Status.DatasetRef = utils.RemoveString(newDataset.Status.DatasetRef, datasetRefName)
-		err := e.Client.Status().Update(context.TODO(), newDataset)
+	if physicalRuntimeInfo != nil {
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/referencedataset/engine.go:203]: Please add log message to indicate `physicalRuntimeInfo == nil` case so that we can know corner case happened.

**Review by TrafalgarZZZ — CHANGES_REQUESTED** [review]

File: pkg/ddc/thin/engine.go (hunk 10 above)
Comment (wangshli) [reply pkg/ddc/thin/engine.go:129]: In this case, `CheckReferenceDatasetRuntime` can't judge whether this dataset is a reference dataset, so we raise the error now. And this case will be repaired by next PR.

File: pkg/ddc/thin/engine.go [hunk 12]
```diff
@@ -61,7 +61,7 @@ func Build(id string, ctx cruntime.ReconcileRequestContext) (base.Engine, error)
 		return nil, fmt.Errorf("engine %s is failed due to type conversion", ctx.Name)
 	}
 
-	isRef, err := CheckReferenceDatasetRuntime(ctx.Client, runtime)
+	isRef, err := CheckReferenceDatasetRuntime(ctx, runtime)
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/engine.go:64]: Maybe in future we can simply check `len(runtime.profileName) == 0` to indicate whether it is a VirtualRuntime or ThinRuntime instead of checking all the dataset mounts.

**Review by TrafalgarZZZ — COMMENTED** [review]
/lgtm

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
