### PR TITLE
Fix reference dataset & Fix NPE bug for eacruntime 

### LINKED ISSUE #2575: [BUG] Failed to use reference dataset for EACRuntime
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
Fix reference dataset for eacruntime & Fix NPE bug for eacruntime

### Ⅱ. Does this pull request fix one issue?

fixes #2575 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/thin/referencedataset/cm.go [hunk 1]
```diff
@@ -129,6 +129,9 @@ func createConfigMapForRefDataset(client client.Client, refDataset *datav1alpha1
 		if err != nil {
 			return err
 		}
+	case common.EACRuntime:
+		// TODO: EACRuntime needs worker-endpoint configmap which should be synced timely for ECI mode.
```
Comment (cheyang) [inline pkg/ddc/thin/referencedataset/cm.go:133]: Will you add logging for `case common.EACRuntime:` ?

Comment (TrafalgarZZZ) [reply pkg/ddc/thin/referencedataset/cm.go:133]: Done
