### PR TITLE
Fix multiple dataset pvc fuse mutation

### LINKED ISSUE #2150: [BUG] Failed to mutate pod when multiple dataset pvcs are mounted
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
Failed to mutate pod when multiple dataset pvcs are mounted

**What you expect to happen:**
The pod should be successfully mutated with multiple fuse sidecar containers 

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
Fix multiple dataset pvc fuse mutation

Use inject index to handle scenario where there are multiple dataset pvcs mounted to one pod. Now the webhook injects fuse containers with names like `fluid-fuse`, `fluid-fuse-1`, `fluid-fuse-2`,... Other volumes that required by fuse containers are also named like `<vol-name>`, `<vol-name>-1`, `<vol-name>-2`,... correspondingly. 

### Ⅱ. Does this pull request fix one issue?

fixes #2150 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/application/inject/fuse/container_test.go [hunk 1]
```diff
@@ -467,16 +467,16 @@ func TestInjectPodWithInitContainer(t *testing.T) {
 								Privileged: &bTrue,
 							}, VolumeMounts: []corev1.VolumeMount{
 								{
-									Name:      "data",
+									Name:      "data-0",
 									MountPath: "/mnt/disk1",
 								}, {
-									Name:      "fuse-device",
+									Name:      "fuse-device-0",
```
Comment (cheyang) [inline pkg/application/inject/fuse/container_test.go:473]: Why does this volumeMount `fuse-device` have index?

**Review by cheyang — APPROVED** [review]
