### PR TITLE
Fix bug 224 by removing duplicated code

### LINKED ISSUE #224: the code repeats[BUG]
**Describe the bug**
In the function `SetupMaster()`,  `"// 2. Update the status of the runtime" `and `"// 3. Update the status of dataset"` are the same code.
[https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/master.go](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/master.go)

```
// setup the cache master
func (e *AlluxioEngine) SetupMaster() (err error) {
	masterName := e.getMasterStatefulsetName()

	// 1. Setup the master
	master, err := e.getMasterStatefulset(masterName, e.namespace)
	if err != nil && apierrs.IsNotFound(err) {
		//1. Is not found error
		e.Log.V(1).Info("SetupMaster", "master", masterName)
		return e.setupMasterInernal()
	} else if err != nil {
		//2. Other errors
		return
	} else {
		//3.The master has been set up
		e.Log.V(1).Info("The master has been set.", "replicas", master.Status.ReadyReplicas)
	}

	// 2. Update the status of the runtime
	err = retry.RetryOnConflict(retry.DefaultBackoff, func() error {
		runtime, err := e.getRuntime()
		if err != nil {
			return err
		}
		runtimeToUpdate := runtime.DeepCopy()

		runtimeToUpdate.Status.MasterPhase = datav1alpha1.RuntimePhaseNotReady
		replicas := runtimeToUpdate.Spec.Master.Replicas
		if replicas == 0 {
			replicas = 1
		}

		runtimeToUpdate.Status.DesiredMasterNumberScheduled = replicas
		runtimeToUpdate.Status.ValueFileConfigmap = e.getConfigmapName()

		if len(runtimeToUpdate.Status.Conditions) == 0 {
			runtimeToUpdate.Status.Conditions = []datav1alpha1.RuntimeCondition{}
		}
		cond := utils.NewRuntimeCondition(datav1alpha1.RuntimeMasterInitialized, datav1alpha1.RuntimeMasterInitializedReason,
			"The master is initialized.", corev1.ConditionTrue)
		runtimeToUpdate.Status.Conditions =
			utils.UpdateRuntimeCondition(runtimeToUpdate.Status.Conditions,
				cond)

		if !reflect.DeepEqual(runtime.Status, runtimeToUpdate.Status) {
			return e.Client.Status().Update(context.TODO(), runtimeToUpdate)
		}

		return nil
	})

	if err != nil {
		e.Log.Error(err, "Update runtime status")
		return err
	}

	// 3. Update the status of dataset
	err = retry.RetryOnConflict(retry.DefaultBackoff, func() error {
		runtime, err := e.getRuntime()
		if err != nil {
			return err
		}
		runtimeToUpdate := runtime.DeepCopy()

		runtimeToUpdate.Status.MasterPhase = datav1alpha1.RuntimePhaseNotReady
		replicas := runtimeToUpdate.Spec.Master.Replicas
		if replicas == 0 {
			replicas = 1
		}

		runtimeToUpdate.Status.DesiredMasterNumberScheduled = replicas
		runtimeToUpdate.Status.ValueFileConfigmap = e.getConfigmapName()

		if len(runtimeToUpdate.Status.Conditions) == 0 {
			runtimeToUpdate.Status.Conditions = []datav1alpha1.RuntimeCondition{}
		}
		cond := utils.NewRuntimeCondition(datav1alpha1.RuntimeMasterInitialized, datav1alpha1.RuntimeMasterInitializedReason,
			"The master is initialized.", corev1.ConditionTrue)
		runtimeToUpdate.Status.Conditions =
			utils.UpdateRuntimeCondition(runtimeToUpdate.Status.Conditions,
				cond)

		if !reflect.DeepEqual(runtime.Status, runtimeToUpdate.Status) {
			return e.Client.Status().Update(context.TODO(), runtimeToUpdate)
		}

		return nil
	})

	if err != nil {
		e.Log.Error(err, "Update runtime status")
		return err
	}

	return
}
```

### PR DESCRIPTION
**Pull request by chaowangnk1**
### Ⅰ. Describe what this PR does
Fix bug 224 by removing duplicated code

### Ⅱ. Does this pull request fix one issue?

fixes #224 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
No test case added, since the PR is only to remove duplicated code and the method is already covered.

### Ⅳ. Describe how to verify it
The code change is verified by running UT and integration test

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/master.go [hunk 1]
```diff
@@ -169,43 +169,5 @@ func (e *AlluxioEngine) SetupMaster() (err error) {
 		return err
 	}
 
-	// 3. Update the status of dataset
```
Comment (xieydd) [inline pkg/ddc/alluxio/master.go:172]: Maybe it need update the status of dataset, but code is duplicated.
You can write how to update status of dataset if you want ：）

Comment (cheyang) [reply pkg/ddc/alluxio/master.go:172]: I think there is no need to update the status of dataset  at the stage of initializing the master.

**Review by xieydd — APPROVED** [review]

**Review by cheyang — APPROVED** [review]

**Comment by cheyang** [comment]
Thanks very much for your contribution. @chaowangnk1
