### PR TITLE
Fix missing syncLocalDir method when loading metadata

### LINKED ISSUE #241: [BUG]Fix missing syncLocalDir method when loading metadata
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
The method `syncLocalDir` is missing when creating PR #225 

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
Fix missing syncLocalDir method when loading metadata

### Ⅱ. Does this pull request fix one issue?

Fixes #241 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/metadata.go [hunk 1]
```diff
@@ -124,10 +125,34 @@ func (e *AlluxioEngine) syncMetadataInternal() (err error) {
 				StartTime: time.Now(),
 				UfsTotal:  "",
 			}
+			dataset, err := utils.GetDataset(e.Client, e.name, e.namespace)
+			if err != nil {
+				result.Err = err
```
Comment (cheyang) [inline pkg/ddc/alluxio/metadata.go:130]: 有没有日志能够标识是什么Error？
