### PR TITLE
fix env sync in juicefs worker

### LINKED ISSUE #3465: [BUG] juicefs workers fail after syncing JuiceFSRuntime's spec
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
1. create Dataset & JuiceFSRuntime
2. edit JuiceFSRuntime with an added env variable. For example: 
```
worker:
    env:
    - name: FOO
      value: BAR
```
3. Found juicefs worker fail to start with the following error
```
$ k logs jfsdemo-worker-0                       
2023/09/18 09:12:50.549948 juicefs auth start.
Failed to fetch configuration from 'https://juicefs.com/volume/%s/mount' for volume 'demo-xxxxxxxxxx', the token or volume is invalid.
2023/09/18 09:12:50.897404 juicefs mount start.
2023-09-18 09:12:50.982790 Configuration file: /root/.juicefs/demo-xxxxxxxxx.conf not exist.
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by zwwhdls**
### Ⅰ. Describe what this PR does
When update env of worker in JuiceFSRuntime, envFrom is synced none.

### Ⅱ. Does this pull request fix one issue?

fixes #3465 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/juicefs/sync_runtime.go [hunk 1]
```diff
@@ -253,20 +253,20 @@ func (j *JuiceFSEngine) isVolumeMountsChanged(crtVolumeMounts, runtimeVolumeMoun
...
 func (j JuiceFSEngine) isEnvsChanged(crtEnvs, runtimeEnvs []corev1.EnvVar) (changed bool, newEnvs []corev1.EnvVar) {
-	envMap := make(map[string]string)
+	envMap := make(map[string]corev1.EnvVar)
 	for _, env := range crtEnvs {
-		envMap[env.Name] = env.Value
+		envMap[env.Name] = env
 	}
 	for _, env := range runtimeEnvs {
-		if envMap[env.Name] != env.Value {
+		if envMap[env.Name].Value != env.Value || envMap[env.Name].ValueFrom != env.ValueFrom {
```
Comment (TrafalgarZZZ) [inline pkg/ddc/juicefs/sync_runtime.go:261]: ValueFrom is a pointer, so `envMap[env.Name].ValueFrom != env.ValueFrom` may not work. How about using `if !reflect.deepEqual(envMap[env.Name], env)`?

**Review by TrafalgarZZZ — CHANGES_REQUESTED** [review]

File: pkg/ddc/juicefs/sync_runtime.go (hunk 1 above)
Comment (zwwhdls) [reply pkg/ddc/juicefs/sync_runtime.go]: done

**Review by cheyang — APPROVED** [review]
/lgtm
/approve

**Review by TrafalgarZZZ — APPROVED** [review]
/lgtm
