### PR TITLE
fix multi cache dir

### LINKED ISSUE #2641: [BUG]JuiceFSRuntime has multi cache dir issue
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by zwwhdls**
### Ⅰ. Describe what this PR does
fix multi cache dir in juicefs runtime

### Ⅱ. Does this pull request fix one issue?

fixes #2641 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/juicefs/transform_fuse.go [hunk 1]
```diff
@@ -230,7 +230,11 @@ func (j *JuiceFSEngine) genValue(mount datav1alpha1.Mount, tiredStoreLevel *data
 	var storagePath = DefaultCacheDir
 	var volumeType = common.VolumeTypeHostPath
 	if tiredStoreLevel != nil {
-		storagePath = tiredStoreLevel.Path // /mnt/disk1/bigboot or /mnt/disk1/bigboot,/mnt/disk2/bigboot
+		// juicefs cache-dir use colon (:) to separate multiple paths
+		// community doc: https://juicefs.com/docs/community/command_reference/#juicefs-mount
+		// enterprise doc: https://juicefs.com/docs/cloud/commands_reference#mount
+		// /mnt/disk1/bigboot or /mnt/disk1/bigboot:/mnt/disk2/bigboot
+		storagePath = tiredStoreLevel.Path
```
Comment (cheyang) [inline pkg/ddc/juicefs/transform_fuse.go:237]: Please fix unit test. thanks.

Comment (zwwhdls) [reply pkg/ddc/juicefs/transform_fuse.go:237]: done

**Review by cheyang — APPROVED** [review]

**Comment by TrafalgarZZZ** [comment]
/hold
hold because multi-dir path won't be cleaned up when shutting down juicefs engine

**Review by cheyang — APPROVED** [review]

File: pkg/ddc/juicefs/operations/base.go [hunk 2]
```diff
@@ -184,6 +184,23 @@ func (j JuiceFileUtils) Mkdir(juiceSubPath string) (err error) {
...
+	)
+	command = append(command, dirs...)
+
+	stdout, stderr, err = j.exec(command, true)
+	if err != nil {
+		err = fmt.Errorf("execute command %v with expectedErr: %v stdout %s and stderr %s", command, err, stdout, stderr)
+		return
+	}
+	return
+}
```
Comment (cheyang) [inline pkg/ddc/juicefs/operations/base.go:202]: To prevent data loss from incorrect directory parameters, I suggest using regular expressions to validate before using "rm -rf" command.  Is it possible for this case?

File: pkg/ddc/juicefs/operations/base.go [hunk 3]
```diff
@@ -184,8 +189,16 @@ func (j JuiceFileUtils) Mkdir(juiceSubPath string) (err error) {
...
 
-// DeleteDirs delete dir in pod
-func (j JuiceFileUtils) DeleteDirs(dirs []string) (err error) {
+// DeleteCacheDirs delete cache dir in pod
+func (j JuiceFileUtils) DeleteCacheDirs(dirs []string) (err error) {
+	for _, dir := range dirs {
+		// cache dir check
+		match := ValidCacheDir(dir)
+		if !match {
+			err = fmt.Errorf("dir %s is not valid", dir)
```
Comment (cheyang) [inline pkg/ddc/juicefs/operations/base.go:198]: How about using the following info？

```golang
err = fmt.Errorf("invalid cache directory %s, skip cleaning up", dir)
```

Comment (zwwhdls) [reply pkg/ddc/juicefs/operations/base.go]: done

Comment (TrafalgarZZZ) [reply pkg/ddc/juicefs/operations/base.go]: @zwwhdls The code now returns an error but I think we should ignore the error if it's not a valid cache dir.
