### PR TITLE
bugfix: support setting jindofs image info in JindoRuntime

### LINKED ISSUE #2966: [BUG] Allow users to set image info in JindoRuntime
**What is your environment(Kubernetes version, Fluid version, etc.)**
Master branch [3dc5427](https://github.com/fluid-cloudnative/fluid/commit/3dc5427f543ea1ebd58a1a04db1943fc5cc65362)

**Describe the bug**
JindoRuntime now refuses to override global-scoped image info (e.g. image, imageTag, imagePullPolicy).

Users should be allowed to set a different image info in JindoRuntime.spec like this:
```
kind: JindoRuntime
spec:
  jindoVersion:
    image: "myimage"
    imageTag: "mytag"
    imagePullPolicy: "IfNotPresent"
  fuse:
    image: "my-fuse-image"
    imageTag: "my-fuse-tag"
    imagePullPolicy: "Always"
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
User should be allowed to override image info like `image`, `imageTag` and `imagePullPolicy` by specifying properties in JindoRuntime. This PR fixes this bug.

For example, with the following configs:
```
# JindoFS global-scoped image in JindoRuntime Controller
jindofs/smartdata: 4.5.2
```

```
kind: JindoRuntime
metadata:
  ...
spec:
  jindoVersion:
    image: xxxxxxx/jindofs/smartdata
    imageTag: 4.5.2-fixed
    imagePullPolicy: IfNotPresent
```

The latter one should override the former.

### Ⅱ. Does this pull request fix one issue?

fixes #2966 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/jindofsx/transform.go [hunk 1]
```diff
@@ -819,45 +820,87 @@ func (e *JindoFSxEngine) transformFuseArg(runtime *datav1alpha1.JindoRuntime, da
...
-func (e *JindoFSxEngine) getSmartDataConfigs() (image, tag, dnsServer string) {
+func (e *JindoFSxEngine) getSmartDataConfigs(runtime *datav1alpha1.JindoRuntime) (image, tag, imagePullPolicy, dnsServer string) {
 	var (
-		defaultImage     = "registry.cn-shanghai.aliyuncs.com/jindofs/smartdata"
-		defaultTag       = "4.5.2"
-		defaultDnsServer = "1.1.1.1"
+		defaultImage           = "registry.cn-shanghai.aliyuncs.com/jindofs/smartdata"
+		defaultTag             = "4.5.2"
+		defaultImagePullPolicy = "Always"
+		defaultDnsServer       = "1.1.1.1"
```
Comment (cheyang) [inline pkg/ddc/jindofsx/transform.go:828]: How about putting default values into a struct? Just like

```golang
defaultValue := smartDataConfig struct {
		image           string
		tag             string
		imagePullPolicy string
		dnsServer       string
	}{
		image:           "registry.cn-shanghai.aliyuncs.com/jindofs/smartdata",
		tag:             "4.5.2",
		imagePullPolicy: "Always",
		dnsServer:       "1.1.1.1",
	},
```

File: pkg/ddc/jindofsx/transform.go [hunk 2]
```diff
@@ -819,45 +820,87 @@ func (e *JindoFSxEngine) transformFuseArg(runtime *datav1alpha1.JindoRuntime, da
...
+		tag = globalTag
+	}
+	if len(globalDnsServer) > 0 {
+		dnsServer = globalDnsServer
 	}
-	if len(tag) == 0 {
-		tag = defaultTag
+
+	// Override with runtime-scoped configs
+	if len(runtime.Spec.JindoVersion.Image) > 0 {
```
Comment (cheyang) [inline pkg/ddc/jindofsx/transform.go:852]: Use switch case instead of if else to improve the readability of the code.
```golang
switch {
case len(runtime.Spec.JindoVersion.Image) > 0:
	image = runtime.Spec.JindoVersion.Image
case len(runtime.Spec.JindoVersion.ImageTag) > 0:
	tag = runtime.Spec.JindoVersion.ImageTag
case len(runtime.Spec.JindoVersion.ImagePullPolicy) > 0:
	imagePullPolicy = runtime.Spec.JindoVersion.ImagePullPolicy
}
```

File: pkg/ddc/jindofsx/transform.go [hunk 3]
```diff
@@ -819,45 +820,87 @@ func (e *JindoFSxEngine) transformFuseArg(runtime *datav1alpha1.JindoRuntime, da
...
+	}
+	if len(globalTag) > 0 {
+		tag = globalTag
+	}
+
+	// Override with runtime-scoped configs
+	runtimeImage := runtime.Spec.Fuse.Image
+	runtimeTag := runtime.Spec.Fuse.ImageTag
+	runtimeImagePullPolicy := runtime.Spec.Fuse.ImagePullPolicy
+	if len(runtimeImage) > 0 {
```
Comment (cheyang) [inline pkg/ddc/jindofsx/transform.go:893]: Ditto

**Review by cheyang — CHANGES_REQUESTED** [review]

File: pkg/ddc/jindofsx/transform.go (hunk 3 above)
Comment (TrafalgarZZZ) [reply pkg/ddc/jindofsx/transform.go]: Done

File: pkg/ddc/jindofsx/transform.go (hunk 1 above)
Comment (TrafalgarZZZ) [reply pkg/ddc/jindofsx/transform.go]: Done.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
