### PR TITLE
make the function setupWorker as common function

### LINKED ISSUE #1103: [BUG]make the function setupWorker as common function
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by cheyang**
Signed-off-by: cheyang <cheyang@163.com>

### Ⅱ. Does this pull request fix one issue?

fixes #1103 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/base/interface.go [hunk 1]
```diff
@@ -0,0 +1,32 @@
...
+*/
+
+package base
+
+import (
+	datav1alpha1 "github.com/fluid-cloudnative/fluid/api/v1alpha1"
+	runtime "k8s.io/apimachinery/pkg/runtime"
+)
+
+type RuntimeInterface interface {
```
Comment (TrafalgarZZZ) [inline pkg/ddc/base/interface.go:23]: I am a little confused about the differences between `RuntimeInterface` and `RuntimeInfoInterface`. So which info should be included in the `RuntimeInterface` and which should be included in the other? Can we refactor these two into one struct?

Comment (cheyang) [reply pkg/ddc/base/interface.go:23]: In the end, I hope every thing will go to `RuntimeInterface`. But for now, the key differences between them is :

1. `RuntimeInterface` is instance of `runtime.Object`, so it can be used by client-go to update in API Server. All the runtime can extend it.
2. `Info` for now just be information of the runtime which engine is uses it for handle.  Once we move the key logic to ctrl package, we can start to deprecate `RuntimeInfoInterface`.

Comment (TrafalgarZZZ) [reply pkg/ddc/base/interface.go:23]: Thx. LGTM

**Review by TrafalgarZZZ — APPROVED** [review]
LGTM
