### PR TITLE
Enhance jindoruntime with default stderr log and worker resource

### LINKED ISSUE #1019: [BUG]Enhance jindoruntime with default stderr log and worker resource
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by frankleaf**
### Ⅱ. Does this pull request fix one issue?

fixes #1019 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: api/v1alpha1/jindoruntime_types.go [hunk 1]
```diff
@@ -150,6 +150,9 @@ type JindoRuntimeSpec struct {
 	// Labels will be added on all the JindoFS pods.
 	// +optional
 	Labels map[string]string `json:"labels,omitempty"`
+
+	// +optional
+	Filelog bool `json:"filelog,omitempty"`
```
Comment (cheyang) [inline api/v1alpha1/jindoruntime_types.go:155]: I like `struct` rather than `boolean` for more possible choices for future. For example we'd like to add log level.

```golang
LogConfig LogConfig `json:"logConfig,omitempty"`
```
Maybe we can refer flink crd.

https://github.com/GoogleCloudPlatform/flink-on-k8s-operator/blob/0310df76d6e2128cd5d2bc51fae4e842d370c463/examples/log_config.yaml#L21

Comment (frankleaf) [reply api/v1alpha1/jindoruntime_types.go:155]: this is reasonable, what about
`LogConfig map[string]string `json:"logConfig,omitempty"``
to define some log option to jindoruntime

Comment (cheyang) [reply api/v1alpha1/jindoruntime_types.go:155]: lgtm

File: pkg/ddc/jindo/transform.go [hunk 2]
```diff
@@ -134,6 +134,8 @@ func (e *JindoEngine) transform(runtime *datav1alpha1.JindoRuntime) (value *Jind
 	}
 	err = e.transformRunAsUser(runtime, value)
 	e.transformTolerations(dataset, runtime, value)
+	e.transformResourcesForWorker(runtime, value)
+	e.transformStderrlogEnable(runtime, value)
```
Comment (cheyang) [inline pkg/ddc/jindo/transform.go:138]: Suggest to rename `transformStderrlogEnable` to `transformLogConfig`

**Review by cheyang — CHANGES_REQUESTED** [review]

File: charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml [hunk 3]
```diff
@@ -218,6 +218,10 @@ spec:
                 type: string
               description: Labels will be added on all the JindoFS pods.
               type: object
+            logConfig:
```
Comment (cheyang) [inline charts/fluid/fluid/crds/data.fluid.io_jindoruntimes.yaml:221]: Please update the chart version of jindo. Thanks.

**Review by cheyang — APPROVED** [review]
