### PR TITLE
fix unexpected override some fields after updating juicefsruntime 

### LINKED ISSUE #5205: [BUG] Unexpected spec overriding when applying JuiceFSRuntime's spec
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
Some env variables are removed unexpectedly when applying a variable into JuiceFSRuntime.spec.fuse.env. These env variables (e.g. META_URL, ACCESS_KEY, and SECRET_KEY) are critical for JuiceFS. So it's possible to cause failure when these env variables are missing.

**What you expect to happen:**
When applying a variable into JuiceFSRuntime.spec.fuse.env, env variables in JuiceFSRuntime's fuse daemonset should be kept, and the new variable should be appended to fuse daemonset's env.

**How to reproduce it**
1. Create Dataset & JuiceFSRuntime 
```yaml
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: jfsdemo
spec:
  placement: Shared
  accessModes: ["ReadWriteMany"]
  mounts:
    - name: minio
      mountPoint: "juicefs:///"
      options:
        bucket: "http://minio:9000/minio/test"
        storage: "minio"
      encryptOptions:
        - name: metaurl
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: metaurl
        - name: access-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: access-key
        - name: secret-key
          valueFrom:
            secretKeyRef:
              name: jfs-secret
              key: secret-key
---
apiVersion: data.fluid.io/v1alpha1
kind: JuiceFSRuntime
metadata:
  name: jfsdemo
spec:
  replicas: 0
  tieredstore:
    levels:
      - mediumtype: MEM
        volumeType: emptyDir
        path: /dev/shm
        quota: 3Gi
        low: "0.1"
```

2. Check JuiceFSRuntime FUSE daemonset's env variables
```yaml
       - name: JFS_FOREGROUND
          value: "1"
        - name: METAURL
          valueFrom:
            secretKeyRef:
              key: metaurl
              name: jfs-secret
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              key: access-key
              name: jfs-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: jfs-secret
        - name: FLUID_RUNTIME_TYPE
          value: juicefs
        - name: FLUID_RUNTIME_NS
          value: default
        - name: FLUID_RUNTIME_NAME
          value: jfsdemo
```

3. Update JuiceFSRuntime.spec.fuse.env
For example:
```diff
  apiVersion: data.fluid.io/v1alpha1
  kind: JuiceFSRuntime
  metadata:
    name: jfsdemo
  spec:
    replicas: 0
+  fuse:
+    env:
+     - name: TEST_ENV
+       value: "true"
    tieredstore:
      levels:
        - mediumtype: MEM
          volumeType: emptyDir
          path: /dev/shm
          quota: 3Gi
          low: "0.1"
```

4. Check JuiceFSRuntime FUSE daemonset's env variables
```
env:
  - name: TEST_ENV
     value: "true"
```

**Additional Information**

### PR DESCRIPTION
**Pull request by Syspretor**
### Ⅱ. Does this pull request fix one issue?

fixes #5205

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/juicefs/sync_runtime.go [hunk 1]
```diff
@@ -452,6 +459,9 @@ func (j JuiceFSEngine) isVolumesChanged(crtVolumes, runtimeVolumes []corev1.Volu
 
 func (j JuiceFSEngine) isLabelsChanged(crtLabels, runtimeLabels map[string]string) (changed bool, newLabels map[string]string) {
 	newLabels = crtLabels
+	if newLabels == nil {
```
Comment (zwwhdls) [inline pkg/ddc/juicefs/sync_runtime.go]: Need to check length?

File: pkg/ddc/juicefs/sync_runtime.go [hunk 2]
```diff
@@ -296,28 +300,31 @@ func (j *JuiceFSEngine) checkAndSetFuseChanges(currentValue, latestValue *JuiceF
 		}
 
 		// env
-		if envChanged, newEnvs := j.isEnvsChanged(currentValue.Fuse.Envs, latestValue.Fuse.Envs); envChanged {
+		if envChanged, newEnvs := j.isEnvsChanged(oldValue.Fuse.Envs, latestValue.Fuse.Envs); envChanged {
 			j.Log.Info("syncFuseSpec envChanged")
-			fusesToUpdate.Spec.Template.Spec.Containers[0].Env = newEnvs
+			fusesToUpdate.Spec.Template.Spec.Containers[0].Env =
+				append(utils.GetEnvsDifference(fusesToUpdate.Spec.Template.Spec.Containers[0].Env, oldValue.Fuse.Envs), newEnvs...)
```
Comment (cheyang) [inline pkg/ddc/juicefs/sync_runtime.go:308]: Do we consider using https://github.com/google/go-cmp in future?

File: pkg/utils/volumes.go [hunk 3]
```diff
@@ -138,3 +138,35 @@ func FilterVolumesByVolumeMounts(volumes []corev1.Volume, volumeMounts []corev1.
...
+		if !volumesRecord[v.Name] {
+			retVolumes = append(retVolumes, v)
+		}
+	}
+	return retVolumes
+}
+
+// GetVolumeMountsDifference calculates the difference between two volume slices,
+// returning volumeMounts that exist in the baseVolumeMounts slice but not in the excludeVolumeMounts slice.
+func GetVolumeMountsDifference(baseVolumeMounts, excludeVolumeMounts []corev1.VolumeMount) []corev1.VolumeMount {
```
Comment (TrafalgarZZZ) [inline pkg/utils/volumes.go]: change `excludeVolumeMounts` to `volumeMountsToExclude` for better readability

File: pkg/ddc/juicefs/sync_runtime.go [hunk 4]
```diff
@@ -257,33 +257,37 @@ func (j *JuiceFSEngine) syncFuseSpec(ctx cruntime.ReconcileRequestContext, runti
...
 		fuseChanged = true
 	}
 
 	// volumes
-	if volumeChanged, newVolumes := j.isVolumesChanged(currentValue.Fuse.Volumes, latestValue.Fuse.Volumes); volumeChanged {
+	if volumeChanged, newVolumes := j.isVolumesChanged(oldValue.Fuse.Volumes, latestValue.Fuse.Volumes); volumeChanged {
 		j.Log.Info("syncFuseSpec volumeChanged")
-		fusesToUpdate.Spec.Template.Spec.Volumes = newVolumes
+		fusesToUpdate.Spec.Template.Spec.Volumes =
+			append(utils.GetVolumesDifference(fusesToUpdate.Spec.Template.Spec.Volumes, oldValue.Fuse.Volumes), newVolumes...)
```
Comment (TrafalgarZZZ) [inline pkg/ddc/juicefs/sync_runtime.go:276]: Pls leave a TODO here to remind that we should use code logic to transform all volumes instead of helm.

Comment (Syspretor) [reply pkg/ddc/juicefs/sync_runtime.go:276]: sure, a TODO has been recorded here

File: pkg/ddc/juicefs/sync_runtime.go (hunk 2 above)
Comment (Syspretor) [reply pkg/ddc/juicefs/sync_runtime.go:308]: Good suggestion, a TODO will be record here

File: pkg/ddc/juicefs/sync_runtime.go (hunk 1 above)
Comment (Syspretor) [reply pkg/ddc/juicefs/sync_runtime.go]: sure, the suggested changes have been made.
