### PR TITLE
Fix default Alluxio writetype config

### LINKED ISSUE #3260: [BUG]Dataset数据不同步到后端存储
**What is your environment(Kubernetes version, Fluid version, etc.)**
k8s1.22.17 
fluid 0.8.5 

**Describe the bug**
配置dataset

```
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: imagenetf
spec:
  mounts:
  - mountPoint: oss://dir
    name: imagenetf
    path: /
    options:
      fs.oss.accessKeyId: ak
      fs.oss.accessKeySecret: sk
      fs.oss.endpoint: 
  accessModes:
    - ReadWriteMany
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - hostname
---
apiVersion: data.fluid.io/v1alpha1
kind: AlluxioRuntime
metadata:
  name: imagenetf
spec:
  replicas: 1
  tieredstore:
    levels:
      - mediumtype: MEM
        path: /dev/shm
        quota: 10Gi
        high: "0.99"
        low: "0.8"
```
pod挂载pvc后，新建文件不会上传到oss，alluxio.user.file.writetype.default默认配置为MUST_CACHE

**What you expect to happen:**
ReadWriteMany默认情况下应该写入后端存储

### PR DESCRIPTION
**Pull request by zhang-x-z**
### Ⅰ. Describe what this PR does
Now Fluid set the default writetype configuration in Alluxio to MUST_CACHE, which makes Alluxio doesn't persist new file to backend storage. I change the default writetype to ASYNC_THROUGH, which is the defalut configuration in Alluxio. Here is [the writetype document](https://docs.alluxio.io/os/user/stable/en/overview/Architecture.html#data-flow-write).

### Ⅱ. Does this pull request fix one issue?

fixes #3260 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/transform_optimization.go [hunk 1]
```diff
@@ -50,7 +50,7 @@ func (e *AlluxioEngine) optimizeDefaultProperties(runtime *datav1alpha1.AlluxioR
 	setDefaultProperties(runtime, value, "alluxio.user.block.worker.client.pool.min", "512")
 	setDefaultProperties(runtime, value, "alluxio.fuse.debug.enabled", "false")
 	setDefaultProperties(runtime, value, "alluxio.web.ui.enabled", "false")
-	setDefaultProperties(runtime, value, "alluxio.user.file.writetype.default", "MUST_CACHE")
+	setDefaultProperties(runtime, value, "alluxio.user.file.writetype.default", "ASYNC_THROUGH")
```
Comment (cheyang) [inline pkg/ddc/alluxio/transform_optimization.go:53]: I think we don't need set the properties, just keep it as alluxio default behavior.

Comment (zhang-x-z) [reply pkg/ddc/alluxio/transform_optimization.go]: The code has been updated.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
