### PR TITLE
fix fuse default args for readOnly and write

### LINKED ISSUE #3159: [BUG] JindoRuntime supports adaptive FUSE cache strategies
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

The Jindoruntime needs to define different FUSE cache strategies based on the read/write characteristics of the dataset. For example, if the dataset is read-only, the kernel_cache option should be configured, and if the dataset is read-write, the autocache option should be configured.

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by frankleaf**
### Ⅱ. Does this pull request fix one issue?

fixes #3159 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/jindofsx/transform.go [hunk 1]
```diff
@@ -820,9 +820,16 @@ func (e *JindoFSxEngine) transformFuseArg(runtime *datav1alpha1.JindoRuntime, da
...
 		fuseArgs = append(fuseArgs, "-okernel_cache")
 		if readOnly {
+			fuseArgs = append(fuseArgs, "-okernel_cache")
 			fuseArgs = append(fuseArgs, "-oro")
 			fuseArgs = append(fuseArgs, "-oattr_timeout=7200")
 			fuseArgs = append(fuseArgs, "-oentry_timeout=7200")
+			fuseArgs = append(fuseArgs, "-onegative_timeout=7200")
+		} else {
+			fuseArgs = append(fuseArgs, "-oauto_cache")
+			fuseArgs = append(fuseArgs, "-oattr_timeout=0")
```
Comment (cheyang) [inline pkg/ddc/jindofsx/transform.go:830]: How about using default value of oattr_timeout, oentry_timeout, onegative_timeout?

File: pkg/ddc/jindofsx/transform.go [hunk 2]
```diff
@@ -820,9 +820,16 @@ func (e *JindoFSxEngine) transformFuseArg(runtime *datav1alpha1.JindoRuntime, da
 	} else {
 		fuseArgs = append(fuseArgs, "-okernel_cache")
```
Comment (cheyang) [inline pkg/ddc/jindofsx/transform.go:821]: `-okernel_cache`  has been enabled twice. Please double chekc.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
