### PR TITLE
change some fields from optional to required in CRD YAML

### LINKED ISSUE #3683: [BUG] The field mountPoint in Dataset spec is optional.
**What is your environment(Kubernetes version, Fluid version, etc.)**
- K8s: 1.22.4
- Fluid: 0.9.2

**Describe the bug**
The dataset without the field `mountPoint` can be applyed. e.g.
```bash
$ cat test-dataset.yaml 
apiVersion: data.fluid.io/v1alpha1
kind: Dataset
metadata:
  name: test-dataset
spec:
  mounts:
    - name: test-dataset
$ kubectl apply -f test-dataset.yaml 
dataset.data.fluid.io/test-dataset created
$ kubectl get dataset
NAME           UFS TOTAL SIZE   CACHED   CACHE CAPACITY   CACHED PERCENTAGE   PHASE      AGE
test-dataset                                                                  NotBound   11s
```
It can be applyed without error.
**What you expect to happen:**
The dataset without `mountPoint` cannot be applyed.
**How to reproduce it**
Just apply the dataset without `mountPoint`.
**Additional Information**

### PR DESCRIPTION
**Pull request by zhang-x-z**
### Ⅰ. Describe what this PR does
Now some fields in Fluid's data types are marked as required, but in the generated CRD, these field is still optional (e.g. the `mountPoint` field). This is because kubebuilder will not make these fields required as these fields is marked with `omitempty`.

This PR removes these required field's `omitempty` and make them required in CRD.

### Ⅱ. Does this pull request fix one issue?

fixes #3683 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: api/v1alpha1/common.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ type Level struct {
 	// Multiple paths should be separated with comma. For example: "/mnt/cache1,/mnt/cache2".
 	// +kubebuilder:validation:MinLength=1
 	// +required
-	Path string `json:"path,omitempty"`
+	Path string `json:"path"`
```
Comment (cheyang) [inline api/v1alpha1/common.go:54]: I think it's optional for some runtime, for example vineyard.

Comment (zhang-x-z) [reply api/v1alpha1/common.go]: Fixed.

**Comment by cheyang** [comment]
@zhang-x-z please fix lint check by running `make gen-openapi`.

**Comment by zhang-x-z** [comment]
> please fix lint check by running `make gen-openapi`.
@cheyang Done. All checks passed.

**Comment by cheyang** [comment]
> > please fix lint check by running `make gen-openapi`.
> 
> @cheyang Done. All checks passed.

I think `mounts` should be omitempty.

**Review by cheyang — APPROVED** [review]
/lgtm
/approve
