### PR TITLE
fix: issue-2367

### LINKED ISSUE #2367: [BUG] Webhook denied request because it failed to find the mountType
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
When using ThinRuntime with Fluid's serverless mode, Fluid webhook will denied the pod create request because it failed to find the prefix by mountType.

```
Error from server: error when creating "pod.yaml": admission webhook "sidecar.fuse.fluid.io" denied the request: failed to find the prefix by mountType ossfs
```

**What you expect to happen:**
Fluid webhook should successfully handle such pod create request.

**How to reproduce it**
1. Create Dataset & ThinRuntime
2. Create Pod with spec like the one specified in the [document](https://github.com/fluid-cloudnative/fluid/blob/master/docs/zh/samples/knative.md) to enable serverless mode
3. The `kubectl create -f pod.yaml` will return the "request denied" error message

**Additional Information**

### PR DESCRIPTION
**Pull request by wang-mask**
Signed-off-by: wang-mask <2018091609006@std.uestc.edu.cn>

### Ⅰ. Describe what this PR does
Fix issue-2367

### Ⅱ. Does this pull request fix one issue?

fixes #2367 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/utils/kubeclient/volume_mount.go [hunk 1]
```diff
@@ -87,6 +87,14 @@ func GetFuseMountInContainer(mountType string, container corev1.Container) (volu
 	if prefix, found := kv[mountType]; found {
 		volumeMountName = prefix + "-fuse-mount"
 	} else {
+		for _, vm := range container.VolumeMounts {
+			if vm.Name == "thin-fuse-mount" {
```
Comment (cheyang) [inline pkg/utils/kubeclient/volume_mount.go:91]: Could you define a constant to reuse "thin-fuse-mount"?
