### PR TITLE
retry find statefulset when destroyMaster

### LINKED ISSUE #775: [BUG]
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

when delete JindoRuntime, if master statefulset deleted early, the delete process will trap in a loop so that the deletion process cannot proceed normally

```
2021-05-12T15:33:49.437+0800 INFO jindoctl.JindoRuntime jindo/cache.go:65 Failed to get master {"jindoruntime": "default/hadoop", "err": "StatefulSet.apps "hadoop-jindofs-master" not found"}
2021-05-12T15:33:49.437+0800 ERROR jindoctl.JindoRuntime.reconcileRuntimeDeletion controllers/runtime_controller.go:158 Failed to shutdown the engine {"jindoruntime": "default/hadoop", "Runtime": {"namespace": "default", "name": "hadoop"}, "error": "StatefulSet.apps "hadoop-jindofs-master" not found"}

```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by frankleaf**
### Ⅰ. Describe what this PR does

when delete JindoRuntime, if master statefulset deleted early, the delete process will trap in a loop so that the deletion process cannot proceed normally

2021-05-12T15:33:49.437+0800	INFO	jindoctl.JindoRuntime	jindo/cache.go:65	Failed to get master	{"jindoruntime": "default/hadoop", "err": "StatefulSet.apps \"hadoop-jindofs-master\" not found"}
2021-05-12T15:33:49.437+0800	ERROR	jindoctl.JindoRuntime.reconcileRuntimeDeletion	controllers/runtime_controller.go:158	Failed to shutdown the engine	{"jindoruntime": "default/hadoop", "Runtime": {"namespace": "default", "name": "hadoop"}, "error": "StatefulSet.apps \"hadoop-jindofs-master\" not found"}

### Ⅱ. Does this pull request fix one issue?

fixes #775 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/cache.go [hunk 1]
```diff
@@ -265,7 +265,7 @@ func (e *AlluxioEngine) invokeCleanCache(path string) (err error) {
 	master, err := e.getMasterStatefulset(masterName, e.namespace)
 	if err != nil {
 		e.Log.Info("Failed to get master", "err", err.Error())
-		return
+		return nil
```
Comment (cheyang) [inline pkg/ddc/alluxio/cache.go:268]: Please use `utils.IgnoreNotFound(err) == nil `

**Review by cheyang — CHANGES_REQUESTED** [review]

**Review by cheyang — APPROVED** [review]
