### PR TITLE
Remove redundant comment task2

### LINKED ISSUE #301: [BUG]redundant comment of helm.go
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by ConnyLamp**
### Ⅰ. Describe what this PR does
Remove remove redundant comment on GenerateHelmTemplate function.(pkg/utils/helm/helm.go)

### Ⅱ. Does this pull request fix one issue?

fixes #301 

### Ⅴ. Special notes for reviews

### CODE REVIEW

**Comment by cheyang** [comment]
Please create an issue on it. Thanks.

**Review by xieydd — COMMENTED** [review]
How about add space after `//`

File: pkg/utils/helm/helm.go [hunk 1]
```diff
@@ -56,11 +56,9 @@ func GenerateValueFile(values interface{}) (valueFileName string, err error) {
 	return valueFileName, err
 }
 
-/**
-* generate helm template without tiller: helm template -f values.yaml chart_name
-* Exec /usr/local/bin/helm, [template -f /tmp/values313606961 --namespace default --name hj /charts/tf-horovod]
-* returns generated template file: templateFileName
- */
+//GenerateHelmTemplate generates helm template without tiller: helm template -f values.yaml chart_name
```
Comment (cheyang) [inline pkg/utils/helm/helm.go:59]: Thanks for the suggestions from @xieydd . 
Please add space between '//' and content. Just like "// GenerateHelmTemplate"

**Review by cheyang — CHANGES_REQUESTED** [review]

**Review by cheyang — APPROVED** [review]
