### PR TITLE
Avoid spread-first scheduling policy for EACRuntime's workers

### LINKED ISSUE #2581: [BUG] Avoid spread-first scheduling policy for EACRuntime's workers.
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

Avoid spread-first scheduling policy for EACRuntime's workers. Currently EAC prefers binpack-first scheduling policy to spread-first scheduling policy. Set PreferredDuringSchedulingIgnoredDuringExecution to empty to avoid using spread-first scheduling policy.

Note：This is a temporary fix and should be removed when EAC is ready for spread-first scheduling policy

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
Signed-off-by: dongyun.xzh <dongyun.xzh@alibaba-inc.com>

### Ⅰ. Describe what this PR does
Avoid spread-first scheduling policy for EACRuntime's workers. Currently EAC prefers binpack-first scheduling policy to spread-first scheduling policy. Set PreferredDuringSchedulingIgnoredDuringExecution to empty to avoid using spread-first scheduling policy.

Note：This is a temporary fix and should be removed when EAC is ready for spread-first scheduling policy

### Ⅱ. Does this pull request fix one issue?

fixes #2581 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ctrl/affinity.go [hunk 1]
```diff
@@ -125,6 +126,13 @@ func (e *Helper) BuildWorkersAffinity(workers *appsv1.StatefulSet) (workersToUpd
 					},
 				},
 			}
+
+			// TODO: remove this when EAC is ready for spread-first scheduling policy
+			// Currently EAC prefers binpack-first scheduling policy to spread-first scheduling policy. Set PreferredDuringSchedulingIgnoredDuringExecution to empty
+			// to avoid using spread-first scheduling policy
+			if e.runtimeInfo.GetRuntimeType() == common.EACRuntime {
+				workersToUpdate.Spec.Template.Spec.Affinity.PodAntiAffinity.PreferredDuringSchedulingIgnoredDuringExecution = []corev1.WeightedPodAffinityTerm{}
```
Comment (cheyang) [inline pkg/ctrl/affinity.go:134]: Could you please add unit test for this change? I think we should track the change by using regression test. thanks.

**Review by cheyang — CHANGES_REQUESTED** [review]

File: pkg/ctrl/affinity.go (hunk 1 above)
Comment (TrafalgarZZZ) [reply pkg/ctrl/affinity.go:134]: Done

**Review by cheyang — APPROVED** [review]
