### PR TITLE
Fix ut for thinRuntime

### LINKED ISSUE #2606: [BUG] transform fuse for thinruntime with err: elements differ
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

```bash
--- FAIL: TestThinEngine_transformFuse (0.01s)
    --- FAIL: TestThinEngine_transformFuse/test (0.01s)
        deepequal.go:27: 
            	Error Trace:	/home/runner/work/fluid/fluid/src/github.com/fluid-cloudnative/fluid/pkg/ddc/thin/deepequal.go:27
            	            				/home/runner/work/fluid/fluid/src/github.com/fluid-cloudnative/fluid/pkg/ddc/thin/deepequal.go:35
            	            				/home/runner/work/fluid/fluid/src/github.com/fluid-cloudnative/fluid/pkg/ddc/thin/transform_fuse_test.go:517
            	Error:      	elements differ
            	            	
            	            	extra elements in list A:
            	            	([]interface {}) (len=1) {
            	            	 (v1.EnvVar) {
            	            	  Name: (string) (len=13) "MOUNT_OPTIONS",
            	            	  Value: (string) (len=7) "a=b,c=d",
            	            	  ValueFrom: (*v1.EnvVarSource)(<nil>)
            	            	 }
            	            	}
            	            	
            	            	
            	            	extra elements in list B:
            	            	([]interface {}) (len=1) {
            	            	 (v1.EnvVar) {
            	            	  Name: (string) (len=13) "MOUNT_OPTIONS",
            	            	  Value: (string) (len=7) "c=d,a=b",
            	            	  ValueFrom: (*v1.EnvVarSource)(<nil>)
            	            	 }
            	            	}
            	            	
            	            	
            	            	listA:
            	            	([]v1.EnvVar) (len=4) {
            	            	 (v1.EnvVar) {
            	            	  Name: (string) (len=1) "a",
            	            	  Value: (string) (len=1) "b",
            	            	  ValueFrom: (*v1.EnvVarSource)(<nil>)
            	            	 },
            	            	 (v1.EnvVar) {
            	            	  Name: (string) (len=1) "b",
            	            	  Value: (string) "",
            	            	  ValueFrom: (*v1.EnvVarSource)({
            	            	   FieldRef: (*v1.ObjectFieldSelector)(<nil>),
            	            	   ResourceFieldRef: (*v1.ResourceFieldSelector)(<nil>),
            	            	   ConfigMapKeyRef: (*v1.ConfigMapKeySelector)({
            	            	    LocalObjectReference: (v1.LocalObjectReference) {
            	            	     Name: (string) (len=7) "test-cm"
            	            	    },
            	            	    Key: (string) "",
            	            	    Optional: (*bool)(<nil>)
            	            	   }),
            	            	   SecretKeyRef: (*v1.SecretKeySelector)(<nil>)
            	            	  })
                  port:
                    type: 0
                    intval: 0
                    strval: ""
                  host: ""
                  scheme: ""
                  httpheaders: []
                tcpsocket: null
                grpc: null
              initialdelayseconds: 1
              timeoutseconds: 1
              periodseconds: 1
              successthreshold: 1
              failurethreshold: 1
              terminationgraceperiodseconds: null
            readinessprobe:
              probehandler:
                exec: null
                httpget:
                  path: /healthz
                  port:
                    type: 0
                    intval: 0
                    strval: ""
                  host: ""
                  scheme: ""
                  httpheaders: []
                tcpsocket: null
                grpc: null
              initialdelayseconds: 1
              timeoutseconds: 1
              periodseconds: 1
              successthreshold: 1
              failurethreshold: 1
              terminationgraceperiodseconds: null
            cachedir: ""
            configvalue: '{"mounts":[{"mountPoint":"abc","options":{"a":"b","c":"d"}}],"targetPath":"/thin/fluid/test/thin-fuse"}'
```

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by cheyang**
### Ⅱ. Does this pull request fix one issue?

fixes #2606 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/thin/transform_fuse_test.go [hunk 1]
```diff
@@ -734,10 +736,47 @@ func TestThinEngine_transformFuseWithDuplicateOptionKey(t1 *testing.T) {
...
 		if !testutil.DeepEqualIgnoringSliceOrder(t1, value.Fuse, wantValue.Fuse) {
 			valueYaml, _ := yaml.Marshal(value.Fuse)
 			wantYaml, _ := yaml.Marshal(wantValue.Fuse)
 			t1.Errorf("transformFuse() \ngot = %v, \nwant = %v", string(valueYaml), string(wantYaml))
 		}
 	})
 }
+
+// sortEnvVarByName sorts the value of an environment variable by its name
+func sortEnvVarByName(envs []corev1.EnvVar, name string) []corev1.EnvVar {
```
Comment (TrafalgarZZZ) [inline pkg/ddc/thin/transform_fuse_test.go:749]: I think we can put these two functions to testutil pkg

**Review by xliuqq — APPROVED** [review]
