### PR TITLE
description(向pkg/ddc/alluxio/health_check_test.go添加许可证声明信息)

### LINKED ISSUE #1116: [BUG]向pkg/ddc/alluxio/health_check_test.go添加许可证声明信息
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by chenf1234**
### Ⅰ. Describe what this PR does
This pr is to add the license notice statement information to the head of the file pkg/ddc/alluxio/health_check_test.go

### Ⅱ. Does this pull request fix one issue?
fixes #1116 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
no tests

### Ⅳ. Describe how to verify it
check out the head of the file pkg/ddc/alluxio/health_check_test.go

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/health_check_test.go [hunk 1]
```diff
@@ -1,3 +1,21 @@
+/*
+
+Copyright <year> The <project-name> Author.
```
Comment (cheyang) [inline pkg/ddc/alluxio/health_check_test.go:3]: This should be `Copyright 2021 The Fluid Author.`

**Review by cheyang — CHANGES_REQUESTED** [review]

File: pkg/ddc/alluxio/health_check_test.go (hunk 1 above)
Comment (chenf1234) [reply pkg/ddc/alluxio/health_check_test.go]: I have revised it. Please check it.

**Review by cheyang — APPROVED** [review]
