### PR TITLE
fix eac-fuse mount options

### LINKED ISSUE #2589: [BUG] eac-fuse mount options error
**What is your environment(Kubernetes version, Fluid version, etc.)**
fluid-0.9.0  (0.9.0-fcf2004)

**Describe the bug**
when eac-worker is disable, the eac-fuse mount options is set with "g_tier_EnableClusterCache=true" and "g_tier_EnableClusterCachePrefetch=true", this will result to eac-fuse access cluster cache error.

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by yangjun289519474**
### Ⅰ. Describe what this PR does
when eac-worker is disabled, eac-fuse mount options "g_tier_EnableClusterCache=true" and "g_tier_EnableClusterCachePrefetch=true" are not set.

### Ⅱ. Does this pull request fix one issue?

fixes #2589 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
no

### Ⅳ. Describe how to verify it
no

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/eac/transform_option.go [hunk 1]
```diff
@@ -48,8 +47,12 @@ func (e *EACEngine) transformMasterOptions(runtime *datav1alpha1.EACRuntime,
 func (e *EACEngine) transformFuseOptions(runtime *datav1alpha1.EACRuntime,
 	value *EAC) (err error) {
 	var options []string
-	options = append(options, "g_tier_EnableClusterCache=true")
-	options = append(options, "g_tier_EnableClusterCachePrefetch=true")
+
+	if runtime.Spec.Worker.Disabled == false {
```
Comment (cheyang) [inline pkg/ddc/eac/transform_option.go:51]: It can be simplified to `if !runtime.Spec.Worker.Disabled`.

File: pkg/ddc/eac/transform_option.go [hunk 2]
```diff
@@ -48,8 +47,12 @@ func (e *EACEngine) transformMasterOptions(runtime *datav1alpha1.EACRuntime,
...
+		options = append(options, "g_tier_EnableClusterCache=true")
+		options = append(options, "g_tier_EnableClusterCachePrefetch=true")
```
Comment (cheyang) [inline pkg/ddc/eac/transform_option.go:53]: Could you please also add unit test for this change? thanks.

**Review by cheyang — APPROVED** [review]
