### PR TITLE
Fix sample

### LINKED ISSUE #1862: [BUG] Fix container network sample
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by cheyang**
### Ⅱ. Does this pull request fix one issue?

fixes #1862 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/const.go [hunk 1]
```diff
@@ -20,42 +20,39 @@ const (
...
 
-	HADOOP_CONF_HDFS_SITE_FILENAME = "hdfs-site.xml"
+	hadoopConfCoreSiteFilename = "core-site.xml"
 
-	HADOOP_CONF_CORE_SITE_FILENAME = "core-site.xml"
-
-	HADOOP_CONF_MOUNT_PATH = "/hdfs-config"
+	hadoopConfMountPath = "/hdfs-config"
 
 	PodRoleType = "role"
```
Comment (TrafalgarZZZ) [inline pkg/ddc/alluxio/const.go:55]: Can we unexport the `PodRoleType` const. It is only used in the `alluxio` package.

Comment (cheyang) [reply pkg/ddc/alluxio/const.go]: Done

**Review by TrafalgarZZZ — APPROVED** [review]
LGTM
