### PR TITLE
Forget prometheus metrics after shutting down engines

### LINKED ISSUE #2725: [BUG] Memory leak when enabling the Prometheus
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by TrafalgarZZZ**
### Ⅰ. Describe what this PR does
1. Forget runtime and dataset metrics after shutting down engines
2. Add dataset metrics (e.g. UfsTotal and FileNum) as a prometheus metric

### Ⅱ. Does this pull request fix one issue?

fixes #2725 

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/base/metadata_sync.go [hunk 1]
```diff
@@ -42,3 +49,22 @@ func SafeSend(ch chan MetadataSyncResult, result MetadataSyncResult) (closed boo
 	ch <- result
 	return false
 }
+
+// RecordDatasetMetrics records dataset-related metrics from the given MetadataSyncResult
+func RecordDatasetMetrics(result MetadataSyncResult, datasetNamespace, datasetName string, log logr.Logger) {
+	if len(result.UfsTotal) != 0 {
+		if ufsTotal, ignoredErr := utils.FromHumanSize(result.UfsTotal); ignoredErr == nil {
```
Comment (cheyang) [inline pkg/ddc/base/metadata_sync.go:56]: ignoredErr is not very descriptive and could be changed to something like parseErr.

File: pkg/ddc/base/metadata_sync.go [hunk 2]
```diff
@@ -42,3 +49,22 @@ func SafeSend(ch chan MetadataSyncResult, result MetadataSyncResult) (closed boo
 	ch <- result
 	return false
 }
+
+// RecordDatasetMetrics records dataset-related metrics from the given MetadataSyncResult
+func RecordDatasetMetrics(result MetadataSyncResult, datasetNamespace, datasetName string, log logr.Logger) {
+	if len(result.UfsTotal) != 0 {
```
Comment (cheyang) [inline pkg/ddc/base/metadata_sync.go:55]: Please add 

```goalng
if datasetNamespace == "" {
		return errors.New("datasetNamespace cannot be empty")
	}
	if datasetName == "" {
		return errors.New("datasetName cannot be empty")
	}
```

File: pkg/ddc/base/metadata_sync.go (hunk 1 above)
Comment (TrafalgarZZZ) [reply pkg/ddc/base/metadata_sync.go]: Done

File: pkg/ddc/juicefs/metadata.go [hunk 3]
```diff
@@ -97,6 +97,7 @@ func (j *JuiceFSEngine) syncMetadataInternal() (err error) {
 					datasetToUpdate := dataset.DeepCopy()
 					datasetToUpdate.Status.UfsTotal = result.UfsTotal
 					datasetToUpdate.Status.FileNum = result.FileNum
+					base.RecordDatasetMetrics(result, datasetToUpdate.Namespace, datasetToUpdate.Name, j.Log)
 					if !reflect.DeepEqual(datasetToUpdate, dataset) {
```
[the remark this answers is not in the document]
Comment (TrafalgarZZZ) [reply pkg/ddc/juicefs/metadata.go]: Thx. Fixed. Now calls `base.RecordDatasetMetrics` only after a successful Update

**Review by cheyang — APPROVED** [review]
