### PR TITLE
reconstruct the logic of updating dataset mountpoint

### LINKED ISSUE #955: [BUG] refactor the logic of updating dataset mountpoint
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by yangyuliufeng**
Signed-off-by: yangyuliufeng <qlw705706@gmail.com>

### Ⅰ. Describe what this PR does
reconstruct the logic of updating dataset mountpoint, including:
①edit the definition of engine
②move some function to utils
③reconstruct some functions
④change some show fields

### Ⅱ. Does this pull request fix one issue?

fixes #955 

### Ⅲ. List the added test cases (unit test/integration test) if any, please explain if no tests are needed.
ADD：TestUpdateMountStatus、TestCalculateMountPointsChanges、TestGetMounts、TestGetUpdateUFSMap
Edit：mock_engine and template_engine_test

### Ⅳ. Describe how to verify it
edit the dataset mount point after the dataset is Bound phase

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: pkg/ddc/alluxio/ufs.go [hunk 1]
```diff
@@ -106,42 +91,38 @@ func (e *AlluxioEngine) UpdateUFS(updatedUFSMap map[string][]string) (err error)
...
 
-	return err
-}
-
-func (e *AlluxioEngine) UpdateOnUFSChange() (updateReady bool, err error) {
-	// 1.get the updated ufs map
-	// updatedUFSMap, err
-	updatedUFSMap, err := e.GetUpdateUFSMap()
+	// 2. if no need to add/remove mount points, return false immediately
+	if len(dataset.Spec.Mounts) == len(dataset.Status.Mounts) {
```
Comment (cheyang) [inline pkg/ddc/alluxio/ufs.go:106]: I think we just use `updateUFSMap` to check if the mount points are changed.

**Review by cheyang — CHANGES_REQUESTED** [review]

File: api/v1alpha1/dataset_types.go [hunk 2]
```diff
@@ -26,19 +26,15 @@ import (
 type DatasetPhase string
 
 const (
-	// Bound to runtime, can't be deleted
-	PendingDatasetPhase DatasetPhase = "Pending"
```
Comment (cheyang) [inline api/v1alpha1/dataset_types.go:30]: Could we  keep `PendingDatasetPhase` ?

File: pkg/ddc/base/engine.go [hunk 3]
```diff
@@ -102,7 +116,7 @@ type Implement interface {
 	// SyncMetadata syncs all metadata from UFS
 	SyncMetadata() (err error)
 
-	// Destroy the Volume
+	// DeleteVolume Destroy the Volume
```
Comment (cheyang) [inline pkg/ddc/base/engine.go:119]: Destroy -> Destroys

File: pkg/utils/dataset.go [hunk 4]
```diff
@@ -89,3 +92,94 @@ func IsTargetPathUnderFluidNativeMounts(targetPath string, dataset datav1alpha1.
...
+		alluxioPathHaveMounted := UFSPathBuilder{}.GenAlluxioMountPath(mount, dataset.Status.Mounts)
+		mountedMountPaths = append(mountedMountPaths, alluxioPathHaveMounted)
+	}
+
+	return specMountPaths, mountedMountPaths, err
+}
+
+// calculateMountPointsChanges compare the spec and status of a dataset to calculate MountPoints Changes
+func calculateMountPointsChanges(specMountPaths, mountedMountPaths []string) (add, remove []string) {
+	add = funk.SubtractString(specMountPaths, mountedMountPaths)
```
Comment (cheyang) [inline pkg/utils/dataset.go:141]: Can we use `SubtractString` rather than importing funk package?

File: pkg/ddc/base/syncs.go [hunk 5]
```diff
@@ -54,11 +56,17 @@ func (t *TemplateEngine) Sync(ctx cruntime.ReconcileRequestContext) (err error)
 		return
 	}
 
-	// 4. Update dataset
-	_, err = t.Implement.UpdateOnUFSChange()
+	// 4. Update dataset mount point
+	updateReady, err := t.Implement.UpdateOnUFSChange()
```
Comment (cheyang) [inline pkg/ddc/base/syncs.go:60]: How about to add `ShouldUpdateOnUFSChange` ?Make it as the same style as `ShouldSetupWorkers`

File: pkg/utils/dataset.go (hunk 4 above)
Comment (TrafalgarZZZ) [reply pkg/utils/dataset.go:141]: I wonder why we use a []sting instead of a set(or map).  Seems it's a diff operation on set data structure

**Review by TrafalgarZZZ — CHANGES_REQUESTED** [review]

**Comment by TrafalgarZZZ** [comment]
One more thought when reading the code:
Maybe it's better to emit an event to inform users that the added or removed fluid-native mounts are ignored? Current impl [here](https://github.com/fluid-cloudnative/fluid/blob/master/pkg/ddc/alluxio/ufs_internal.go#L184)

File: pkg/ddc/alluxio/ufs_internal.go [hunk 6]
```diff
@@ -96,85 +98,16 @@ func (e *AlluxioEngine) shouldMountUFS() (should bool, err error) {
...
 	}
 
 	podName, containerName := e.getMasterPodInfo()
-	fileUitls := operations.NewAlluxioFileUtils(podName, containerName, e.namespace, e.Log)
+	fileUtils := operations.NewAlluxioFileUtils(podName, containerName, e.namespace, e.Log)
 
-	ready := fileUitls.Ready()
+	ready := fileUtils.Ready()
 	if !ready {
 		return fmt.Errorf("the UFS is not ready")
```
Comment (allenhaozi) [inline pkg/ddc/alluxio/ufs_internal.go:112]: Add more logs for debugging
```go
return fmt.Errorf("the UFS is not ready,namespace:%s,podName:%s,container:%s",
                    e.namespace,
                    podName,
                    containerName
                    )
```

File: pkg/ddc/alluxio/ufs_internal.go [hunk 7]
```diff
@@ -220,13 +153,22 @@ func (e *AlluxioEngine) processUpdatingUFS(updatedUFSMap map[string][]string) (e
 	// unmount the mount point in the removed array
 	removed := updatedUFSMap["removed"]
```
Comment (allenhaozi) [inline pkg/ddc/alluxio/ufs_internal.go:154]: use a struct to avoid hardcode removed
```go
type UFSUpdatePath struct {
       Removed []string
       Added   []string
}
```

File: pkg/ddc/alluxio/ufs_internal.go [hunk 8]
```diff
@@ -220,13 +153,22 @@ func (e *AlluxioEngine) processUpdatingUFS(updatedUFSMap map[string][]string) (e
...
 			}
 		}
 	}
+	// need to reset ufsTotal to Calculating so that SyncMetadata will work
+	datasetToUpdate := dataset.DeepCopy()
+	datasetToUpdate.Status.UfsTotal = METADATA_SYNC_NOT_DONE_MSG
+	if !reflect.DeepEqual(dataset.Status, datasetToUpdate.Status) {
+		err = e.Client.Status().Update(context.TODO(), datasetToUpdate)
+		if err != nil {
+			e.Log.Error(err, "fail to reset ufsTotal to Calculating")
```
Comment (allenhaozi) [inline pkg/ddc/alluxio/ufs_internal.go:169]:
```go
e.Log.Error(err, "update dataset status UfsTotal failed")

```

File: pkg/ddc/alluxio/ufs.go (hunk 1 above)
Comment (yangyuliufeng) [reply pkg/ddc/alluxio/ufs.go:106]: @cheyang @TrafalgarZZZ It's just used to quickly exit.

File: pkg/utils/dataset.go [hunk 9]
```diff
@@ -89,3 +92,94 @@ func IsTargetPathUnderFluidNativeMounts(targetPath string, dataset datav1alpha1.
 
 	return false
 }
+
+// GetUpdateUFSMap get a map of mount points to be added and removed
+func GetUpdateUFSMap(dataset *datav1alpha1.Dataset) (map[string][]string, error) {
```
[the remark this answers is not in the document]
Comment (yangyuliufeng) [reply pkg/utils/dataset.go:97]: > Seems no need to return an error here? `func getMounts` won't throw any error according to its implementation.

yes

**Review by TrafalgarZZZ — APPROVED** [review]
lgtm

File: pkg/utils/dataset.go [hunk 10]
```diff
@@ -89,3 +97,82 @@ func IsTargetPathUnderFluidNativeMounts(targetPath string, dataset datav1alpha1.
 
 	return false
 }
+
+// GetUFSToUpdate get a UFSToUpdate of mount points to be added and removed
+func GetUFSToUpdate(dataset *datav1alpha1.Dataset) (ufsToUpdate UFSToUpdate) {
+	// get spec MountPaths and mounted MountPaths from dataset
+	specMountPaths, mountedMountPaths := getMounts(dataset)
+	// get mount points which are needed to be added/removed
+	ufsToUpdate.ToAdd, ufsToUpdate.ToRemove = calculateMountPointsChanges(specMountPaths, mountedMountPaths)
```
Comment (allenhaozi) [inline pkg/utils/dataset.go:106]: Provide a proposed implementation
```go
type UFSToUpdate struct {
    ToAdd    []string
    ToRemove []string
}

func (u *UFSToUpdate) CalPathsDelta(ds *datav1alpha1.Dataset){
         for _, mount := range dataset.Spec.Mounts {
		if common.IsFluidNativeScheme(mount.MountPoint) {
			continue
		}
		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, dataset.Spec.Mounts)
		desireMountPaths = append(desireMountPaths, m)
	}
	for _, mount := range dataset.Status.Mounts {
		if common.IsFluidNativeScheme(mount.MountPoint) {
			continue
		}
		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, dataset.Status.Mounts)
		mountedMountPaths = append(currentMountPaths, m)
	}

     u.ToAdd = SubtractString(desireMountPaths, currentMountPaths)
     u.ToRemove = SubtractString(currentMountPaths, desireMountPaths)
}
```

Comment (cheyang) [reply pkg/utils/dataset.go:106]: Thanks for @allenhaozi 's great suggestions! Can we make the methods to encapsulate into `UFSToUpdate`.

```
type UFSToUpdate struct {
    toAdd    []string
    toRemove []string
    dataset *datav1alpha1.Dataset
}

func NewUFSToUpdate(ds *datav1alpha1.Dataset) *UFSToUpdate{
	return &UFSToUpdate{
		dataset: ds,
	}
}

func (u *UFSToUpdate) AnalyzePathsDelta(){
         for _, mount := range u.dataset.Spec.Mounts {
		if common.IsFluidNativeScheme(mount.MountPoint) {
			continue
		}
		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, u.dataset.Spec.Mounts)
		desireMountPaths = append(desireMountPaths, m)
	}
	for _, mount := range u.dataset.Status.Mounts {
		if common.IsFluidNativeScheme(mount.MountPoint) {
			continue
		}
		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, u.dataset.Status.Mounts)
		mountedMountPaths = append(currentMountPaths, m)
	}

     u.toAdd = SubtractString(desireMountPaths, currentMountPaths)
     u.toRemove = SubtractString(currentMountPaths, desireMountPaths)
}

func (u UFSToUpdate)ShouldUpdate() bool {
	return len(u.toAdd) > 0 && len(u.toRemove) > 0
}

func (u UFSToUpdate)ToAdd() []string {
	return u.toAdd
}

func (u UFSToUpdate)ToRemove() []string {
	return u.toRemove
}


```

Comment (yangyuliufeng) [reply pkg/utils/dataset.go]: > Thanks for @allenhaozi 's great suggestions! Can we make the methods to encapsulate into `UFSToUpdate`.
> 
> ```
> type UFSToUpdate struct {
>     toAdd    []string
>     toRemove []string
>     dataset *datav1alpha1.Dataset
> }
> 
> func NewUFSToUpdate(ds *datav1alpha1.Dataset) *UFSToUpdate{
> 	return &UFSToUpdate{
> 		dataset: ds,
> 	}
> }
> 
> func (u *UFSToUpdate) AnalyzePathsDelta(){
>          for _, mount := range u.dataset.Spec.Mounts {
> 		if common.IsFluidNativeScheme(mount.MountPoint) {
> 			continue
> 		}
> 		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, u.dataset.Spec.Mounts)
> 		desireMountPaths = append(desireMountPaths, m)
> 	}
> 	for _, mount := range u.dataset.Status.Mounts {
> 		if common.IsFluidNativeScheme(mount.MountPoint) {
> 			continue
> 		}
> 		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, u.dataset.Status.Mounts)
> 		mountedMountPaths = append(currentMountPaths, m)
> 	}
> 
>      u.toAdd = SubtractString(desireMountPaths, currentMountPaths)
>      u.toRemove = SubtractString(currentMountPaths, desireMountPaths)
> }
> 
> func (u UFSToUpdate)ShouldUpdate() bool {
> 	return len(u.toAdd) > 0 && len(u.toRemove) > 0
> }
> 
> func (u UFSToUpdate)ToAdd() []string {
> 	return u.toAdd
> }
> 
> func (u UFSToUpdate)ToRemove() []string {
> 	return u.toRemove
> }
> ```
```
func (u UFSToUpdate)ShouldUpdate() bool {
	return len(u.toAdd) > 0 || len(u.toRemove) > 0
}
```

**Review by cheyang — APPROVED** [review]

File: pkg/utils/dataset.go [hunk 11]
```diff
@@ -89,3 +91,95 @@ func IsTargetPathUnderFluidNativeMounts(targetPath string, dataset datav1alpha1.
...
+	for _, mount := range u.dataset.Status.Mounts {
+		if common.IsFluidNativeScheme(mount.MountPoint) {
+			continue
+		}
+		m := UFSPathBuilder{}.GenAlluxioMountPath(mount, u.dataset.Status.Mounts)
+		mountedMountPaths = append(mountedMountPaths, m)
+	}
+
+	u.toAdd = SubtractString(specMountPaths, mountedMountPaths)
+	u.toRemove = SubtractString(mountedMountPaths, specMountPaths)
```
Comment (allenhaozi) [inline pkg/utils/dataset.go:168]: Recommend one calculation to reduce traversal, like the following code
```go

// removed: in old and not in new
// added: in new and not in old
func diff(oldList, newList []string) (added, removed []string) {

	newListIndex := map[string]int{}

	// intersection
	// in old and in new
	// marked new index
	intersection := map[int]int{}

	// create index for new data
	for index, v := range newList {
		newListIndex[v] = index
	}

	for _, item := range oldList {
		// in new list and in old list
		if index, ok := newListIndex[item]; ok {
			intersection[index] = index
		} else {
			// in old not in new
			removed = append(removed, item)
		}
	}

	for loop := 0; loop < len(newList); loop++ {
		// in new and not in old
		if _, ok := intersection[loop]; !ok {
			added = append(added, newList[loop])
		}
	}

	return
}
```

File: pkg/utils/dataset.go [hunk 12]
```diff
@@ -89,3 +91,95 @@ func IsTargetPathUnderFluidNativeMounts(targetPath string, dataset datav1alpha1.
...
+
+// UFSToUpdate records the mountPath to change in virtual file system of dataset
+type UFSToUpdate struct {
+	toAdd    []string
+	toRemove []string
+	dataset  *datav1alpha1.Dataset
+}
+
+// NewUFSToUpdate get UFSToUpdate according the given dataset
+func NewUFSToUpdate(ds *datav1alpha1.Dataset) *UFSToUpdate {
```
Comment (allenhaozi) [inline pkg/utils/dataset.go:143]: LGTM
