### PR TITLE
Fix the failure of starting  fluid-csi 

### LINKED ISSUE #239: [BUG] Failed to start csi after adding version flag
**What is your environment(Kubernetes version, Fluid version, etc.)**

**Describe the bug**
fix the bug that fluid-csi cannot read parameter because sending two parameter into one variable.

**What you expect to happen:**

**How to reproduce it**

**Additional Information**

### PR DESCRIPTION
**Pull request by yangyuliufeng**
### Ⅰ. Describe what this PR does
when fluid-csi starts，it will print version info by golog. After starting, users can query version info by command "fluid-csi version".
edit the makefile and dockerfile.csi.

### Ⅱ. Does this pull request fix one issue?
fixes #239 

### Ⅳ. Describe how to verify it
I have verified it with the building command "docker build --no-cache . -f Dockerfile.csi -t xxx".

### Ⅴ. Special notes for reviews

### CODE REVIEW

File: Makefile [hunk 1]
```diff
@@ -19,8 +19,8 @@ GOBIN=$(shell go env GOBIN)
 endif
 
 CURRENT_DIR=$(shell pwd)
-VERSION=v0.4.0
-BUILD_DATE=$(shell date -u +'%Y-%m-%dT%H:%M:%SZ')
+VERSION=0.4.0
```
Comment (cheyang) [inline Makefile:22]: 把v0.4.0改成0.4.0原因？

File: version.go [hunk 2]
```diff
@@ -51,4 +52,38 @@ func GetVersion() Version {
...
+	glog.Infof("BuildDate: %s\n", v.BuildDate)
+	glog.Infof("GitCommit: %s\n", v.GitCommit)
+	glog.Infof("GitTreeState: %s\n", v.GitTreeState)
+	if v.GitTag != "" {
+		glog.Infof("GitTag: %s\n", v.GitTag)
+	}
+	glog.Infof("GoVersion: %s\n", v.GoVersion)
+	glog.Infof("Compiler: %s\n", v.Compiler)
+	glog.Infof("Platform: %s\n", v.Platform)
+	return
```
Comment (cheyang) [inline version.go:88]: 去掉return吧

File: version.go [hunk 3]
```diff
@@ -51,4 +52,38 @@ func GetVersion() Version {
...
+	fmt.Printf("  BuildDate: %s\n", v.BuildDate)
+	fmt.Printf("  GitCommit: %s\n", v.GitCommit)
+	fmt.Printf("  GitTreeState: %s\n", v.GitTreeState)
+	if v.GitTag != "" {
+		fmt.Printf("  GitTag: %s\n", v.GitTag)
+	}
+	fmt.Printf("  GoVersion: %s\n", v.GoVersion)
+	fmt.Printf("  Compiler: %s\n", v.Compiler)
+	fmt.Printf("  Platform: %s\n", v.Platform)
+	return
```
Comment (cheyang) [inline version.go:73]: 去掉return吧

**Review by cheyang — CHANGES_REQUESTED** [review]
